from multiprocessing import managers
from urllib import response
from django.shortcuts import render
from rest_framework.decorators import api_view
from rest_framework.response import Response

from assignments.models import assignments
from assignments.serializeers import AssignmentSerializer
from django.http import HttpResponse
import random
import string

# Create your views here.


#view for GET request for viewwing all assignments
@api_view(['GET'])
def view_task(request):
    assignments_objects = assignments.objects.all() #fetching all the data from assignments table/Model
    serializer = AssignmentSerializer(assignments_objects, many = True) # sending it to serializer for converting to Json
    return Response(serializer.data) # Returning the response to web



#View for POST requests and Adding a new Assignments
@api_view(['POST'])
def new_task(request):
    serializer = AssignmentSerializer(data=request.data) # sending it to serializer for converting and 
    if serializer.is_valid():
        serializer.save() #validating and saving the POSTED data to DB.
        return Response(serializer.data) 
    else:
        return Response(serializer.errors) #else returning the errors generated by serializers.


