# Generated by Django 4.0.5 on 2022-06-05 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignments_createdat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignments',
            old_name='createdat',
            new_name='createdAt',
        ),
    ]
