# Generated by Django 4.0.5 on 2022-06-05 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_rename_createdat_assignments_createdat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignments',
            options={'verbose_name_plural': 'assignment'},
        ),
    ]
