# Generated by Django 4.0.5 on 2022-06-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_alter_assignments_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
